services:
    user-service:
        build:
            context: .
            dockerfile: platforms/microservices/user-service/Dockerfile.dev
        container_name: user-service-dev
        ports:
            - '4002:4002'
        environment:
            - NODE_ENV=development
            - PORT=4002
            # Ici, on n'injecte pas CONNECTION_STRING car le .env est monté
        volumes:
            - ./platforms/microservices/user-service:/app/platforms/microservices/user-service
            - ./platforms/services/base-classes:/app/platforms/services/base-classes
            - ./platforms/services/data-access-layer:/app/platforms/services/data-access-layer
            - ./platforms/microservices/user-service/.env:/app/platforms/microservices/user-service/.env
        networks:
            - api_network
        command: ['npm', 'run', 'dev']

    restaurant-service:
        build:
            context: .
            dockerfile: platforms/microservices/restaurant-service/Dockerfile.dev
        container_name: restaurant-service-dev
        ports:
            - '4003:4003'
        environment:
            - NODE_ENV=development
            - PORT=4003
        volumes:
            - ./platforms/microservices/restaurant-service:/app/platforms/microservices/restaurant-service
            - ./platforms/services/base-classes:/app/platforms/services/base-classes
            - ./platforms/services/data-access-layer:/app/platforms/services/data-access-layer
            - ./platforms/microservices/restaurant-service/.env:/app/platforms/microservices/restaurant-service/.env
        networks:
            - api_network
        command: ['npm', 'run', 'dev']

    nginx-gateway:
        build:
            context: .
            dockerfile: platforms/nginx-gateway/Dockerfile
        container_name: nginx-gateway-dev
        ports:
            - '8080:80'
        environment:
            - NGINX_PORT=8080
            - NGINX_HOST=localhost
        networks:
            - api_network

    mongodb-user:
        image: mongo:latest
        container_name: mongodb-user
        ports:
            - '27017:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/user-service
              target: /data/db
        networks:
            - api_network

    mongodb-restaurant:
        image: mongo:latest
        container_name: mongodb-restaurant
        ports:
            - '27018:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/restaurant-service
              target: /data/db
        networks:
            - api_network

    # sqlserver-auth:
    #    image: mcr.microsoft.com/mssql/server:2019-latest
    #    container_name: sqlserver-auth
    #    environment:
    #        SA_PASSWORD: 'YourStrong!Passw0rd'
    #        ACCEPT_EULA: 'Y'
    #    ports:
    #        - '1433:1433'
    #    volumes:
    #        - type: bind
    #          source: ./platforms/data/sqlserver/auth-service
    #          target: /var/opt/mssql
    #    networks:
    #        - api_network

networks:
    api_network:
        driver: bridge
