services:
    user-service:
        build:
            context: .
            dockerfile: platforms/microservices/user-service/Dockerfile
        container_name: user-service
        ports:
            - '4002:4002'
        env_file:
            - ./platforms/microservices/user-service/.env
        volumes:
            - ./platforms/microservices/user-service:/app/platforms/microservices/user-service
            - ./platforms/services/base-classes:/app/platforms/services/base-classes
            - ./platforms/services/data-access-layer:/app/platforms/services/data-access-layer
        networks:
            - api_network
        command: ['npm', 'run', 'start']

    restaurant-service:
        build:
            context: .
            dockerfile: platforms/microservices/restaurant-service/Dockerfile
        container_name: restaurant-service
        ports:
            - '4003:4003'
        env_file:
            - ./platforms/microservices/restaurant-service/.env
        volumes:
            - ./platforms/microservices/restaurant-service:/app/platforms/microservices/restaurant-service
            - ./platforms/services/base-classes:/app/platforms/services/base-classes
            - ./platforms/services/data-access-layer:/app/platforms/services/data-access-layer
        networks:
            - api_network
        command: ['npm', 'run', 'start']

    mongodb-user:
        image: mongo:latest
        container_name: db-mongodb-user
        ports:
            - '27019:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/user-service
              target: /data/db
        networks:
            - api_network

    mongodb-restaurant:
        image: mongo:latest
        container_name: db-mongodb-restaurant
        ports:
            - '27018:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/restaurant-service
              target: /data/db
        networks:
            - api_network

    mssql-auth-service:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: db-mssql-auth
        ports:
            - '1433:1433'
        # env_file:
        #    - ./platforms/microservices/auth-service/.env
        volumes:
            - ./platforms/data/sqlserver/auth-service/data:/var/opt/mssql/data
            - ./platforms/data/sqlserver/auth-service/log:/var/opt/mssql/log
            - ./platforms/data/sqlserver/auth-service/secrets:/var/opt/mssql/secrets
        networks:
            - api_network

    nginx-gateway:
        build:
            context: .
            dockerfile: platforms/nginx-gateway/D
