services:
    user-service:
        build:
            context: .
            dockerfile: platforms/microservices/user-service/Dockerfile
        container_name: user-service-staging
        ports:
            - '5002:4002'
        env_file:
            - ./platforms/microservices/user-service/.env.staging
        volumes:
            - ./platforms/services/base-classes:/app/platforms/services/base-classes
            - ./platforms/services/data-access-layer:/app/platforms/services/data-access-layer
        networks:
            - api_network
        depends_on:
            - db-mongodb-user

    restaurant-service:
        build:
            context: .
            dockerfile: platforms/microservices/restaurant-service/Dockerfile
        container_name: restaurant-service-staging
        ports:
            - '5003:4003'
        env_file:
            - ./platforms/microservices/restaurant-service/.env.staging
        volumes:
            - ./platforms/services/base-classes:/app/platforms/services/base-classes
            - ./platforms/services/data-access-layer:/app/platforms/services/data-access-layer
        networks:
            - api_network
        depends_on:
            - db-mongodb-restaurant

    db-mongodb-user:
        image: mongo:latest
        container_name: db-mongodb-user-staging
        ports:
            - '37019:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/user-service
              target: /data/db
        networks:
            - api_network

    db-mongodb-restaurant:
        image: mongo:latest
        container_name: db-mongodb-restaurant-staging
        ports:
            - '37018:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/restaurant-service
              target: /data/db
        networks:
            - api_network

    db-mssql-auth:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: db-mssql-auth-staging
        ports:
            - '1435:1433'
        volumes:
            - ./platforms/data/sqlserver/auth-service/data:/var/opt/mssql/data
            - ./platforms/data/sqlserver/auth-service/log:/var/opt/mssql/log
            - ./platforms/data/sqlserver/auth-service/secrets:/var/opt/mssql/secrets
        # env_file:
        #    - ./platforms/microservices/auth-service/.env.staging
        networks:
            - api_network

    nginx-gateway:
        build:
            context: .
            dockerfile: platforms/nginx-gateway/Dockerfile
        container_name: nginx-gateway-staging
        ports:
            - '8081:80'
        networks:
            - api_network

networks:
    api_network:
        driver: bridge
