services:
    user-service:
        build:
            context: .
            dockerfile: platforms/microservices/user-service/Dockerfile
        container_name: user-service
        ports:
            - '4002:4002'
        environment:
            - NODE_ENV=production
            - PORT=4002
            - CONNECTION_STRING=mongodb://mongodb-user:27017/user_db
        networks:
            - api_network

    restaurant-service:
        build:
            context: .
            dockerfile: platforms/microservices/restaurant-service/Dockerfile
        container_name: restaurant-service
        ports:
            - '4003:4003'
        environment:
            - NODE_ENV=production
            - PORT=4003
            - CONNECTION_STRING=mongodb://mongodb-restaurant:27017/restaurant_db
        networks:
            - api_network

    nginx-gateway:
        build:
            context: .
            dockerfile: platforms/nginx-gateway/Dockerfile
        container_name: nginx-gateway
        ports:
            - '8080:80'
        environment:
            - NGINX_PORT=8080
            - NGINX_HOST=prod.example.com
        networks:
            - api_network

    mongodb-user:
        image: mongo:latest
        container_name: mongodb-user
        ports:
            - '27017:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/user-service
              target: /data/db
        networks:
            - api_network

    mongodb-restaurant:
        image: mongo:latest
        container_name: mongodb-restaurant
        ports:
            - '27018:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/restaurant-service
              target: /data/db
        networks:
            - api_network

    # sqlserver-auth:
    #    image: mcr.microsoft.com/mssql/server:2019-latest
    #    container_name: sqlserver-auth
    #    environment:
    #        SA_PASSWORD: 'YourStrong!Passw0rd'
    #        ACCEPT_EULA: 'Y'
    #    ports:
    #        - '1433:1433'
    #    volumes:
    #        - type: bind
    #          source: ./platforms/data/sqlserver/auth-service
    #          target: /var/opt/mssql
    #    networks:
    #        - api_network

networks:
    api_network:
        driver: bridge
