services:
    auth-service:
        build:
            context: .
            dockerfile: platforms/microservices/auth-service/Dockerfile
        container_name: auth-service-prod
        ports:
            - '4001:4001'
        env_file:
            - ./platforms/microservices/auth-service/.env.production
        networks:
            - api_network
        command: ['npm', 'start']

    user-service:
        build:
            context: .
            dockerfile: platforms/microservices/user-service/Dockerfile
        container_name: user-service-prod
        ports:
            - '4002:4002'
        env_file:
            - ./platforms/microservices/user-service/.env.production
        networks:
            - api_network
        command: ['npm', 'start']

    restaurant-service:
        build:
            context: .
            dockerfile: platforms/microservices/restaurant-service/Dockerfile
        container_name: restaurant-service-prod
        ports:
            - '4003:4003'
        env_file:
            - ./platforms/microservices/restaurant-service/.env.production
        networks:
            - api_network
        command: ['npm', 'start']

    mongodb-user:
        image: mongo:latest
        container_name: db-mongodb-user-prod
        ports:
            - '27019:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/user-service
              target: /data/db
        networks:
            - api_network

    mongodb-restaurant:
        image: mongo:latest
        container_name: db-mongodb-restaurant-prod
        ports:
            - '27018:27017'
        volumes:
            - type: bind
              source: ./platforms/data/mongodb/restaurant-service
              target: /data/db
        networks:
            - api_network

    mssql-auth-service:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: db-mssql-auth-prod
        ports:
            - '1433:1433'
        volumes:
            - ./platforms/databases/sqlserver/auth-service/data:/var/opt/mssql/data
            - ./platforms/databases/sqlserver/auth-service/log:/var/opt/mssql/log
            - ./platforms/databases/sqlserver/auth-service/secrets:/var/opt/mssql/secrets
        environment:
            - SA_PASSWORD=ProdPassword123!
            - ACCEPT_EULA=Y
            - MSSQL_UID=10001
        user: '10001:0'
        networks:
            - api_network

networks:
    api_network:
        driver: bridge
