name: CI/CD Pipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  # -----------------------------
  # JOB 1 : Build des projets NPM (plateformes et microservices)
  # -----------------------------
  build-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - "platforms/services/ModelGenerator"
          - "platforms/services/base-classes"
          - "platforms/services/data-access-layer"
          - "platforms/microservices/user-service"
          - "platforms/microservices/restaurant-service"
        node-version: ["22.14"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.project }}

      - name: Build NPM project
        run: npm run build --if-present
        working-directory: ${{ matrix.project }}

  # -----------------------------
  # JOB 2 : Build des apps Yarn (front-end)
  # -----------------------------
  build-yarn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ "customer-final" ]
        node-version: ["22.14"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Yarn install (monorepo)
        run: yarn install --frozen-lockfile

      - name: Build app components
        run: |
          components=(proxy local-middleware front)
          for component in "${components[@]}"; do
            componentDir="apps/${{ matrix.app }}/$component"
            if [ -d "$componentDir" ]; then
              echo "Building $component for app ${{ matrix.app }}..."
              cd "$componentDir"
              yarn build
              cd - > /dev/null
            else
              echo "Directory $componentDir does not exist, skipping."
            fi
          done
